import six

heroes = {
    "*Adagio*": "Adagio",
    "*Alpha*": "Alpha",
    "*Ardan*": "Ardan",
    "*Baron*": "Baron",
    "*Blackfeather*": "Blackfeather",
    "*Catherine*": "Catherine",
    "*Celeste*": "Celeste",
    "*Flicker*": "Flicker",
    "*Fortress*": "Fortress",
    "*Glaive*": "Glaive",
    "*Gwen*": "Gwen",
    "*Hero009*": "Krul",
    "*Hero010*": "Skaarf",
    "*Hero016*": "Rona",
    "*Idris*": "Idris",
    "*Joule*": "Joule",
    "*Kestrel*": "Kestrel",
    "*Koshka*": "Koshka",
    "*Lance*": "Lance",
    "*Lyra*": "Lyra",
    "*Ozo*": "Ozo",
    "*Petal*": "Petal",
    "*Phinn*": "Phinn",
    "*Reim*": "Reim",
    "*Ringo*": "Ringo",
    "*Samuel*": "Samuel",
    "*SAW*": "SAW",
    "*Sayoc*": "Taka",
    "*Skye*": "Skye",
    "*Vox*": "Vox",
    "*Grumpjaw*": "Grumpjaw"
}

heroes_inv = {v.lower(): k for k, v in six.iteritems(heroes)}

hero_roles = {
    "*Adagio*": "Lane, Jungle, Protector",
    "*Alpha*": "Jungle, Warrior",
    "*Ardan*": "Jungle, Protector",
    "*Baron*": "Lane, Sniper",
    "*Blackfeather*": "Lane, Assassin",
    "*Catherine*": "Jungle, Protector",
    "*Celeste*": "Lane, Mage",
    "*Flicker*": "Jungle, Protector",
    "*Fortress*": "Jungle, Protector",
    "*Glaive*": "Jungle, Warrior",
    "*Gwen*": "Lane, Sniper",
    "*Hero009*": "Jungle, Warrior",
    "*Hero010*": "Lane, Mage",
    "*Hero016*": "Jungle, Warrior",
    "*Idris*": "Jungle, Assassin",
    "*Joule*": "Jungle, Warrior",
    "*Kestrel*": "Lane, Sniper",
    "*Koshka*": "Jungle, Assassin",
    "*Lance*": "Jungle, Protector",
    "*Lyra*": "Jungle, Protector",
    "*Ozo*": "Jungle, Assassin",
    "*Petal*": "Jungle, Sniper",
    "*Phinn*": "Jungle, Protector",
    "*Reim*": "Jungle, Mage",
    "*Ringo*": "Lane, Sniper",
    "*Samuel*": "Lane, Mage",
    "*SAW*": "Lane, Sniper",
    "*Sayoc*": "Jungle, Assassin",
    "*Skye*": "Lane, Sniper",
    "*Vox*": "Lane, Sniper",
    "*Grumpjaw*": "Jungle, Warrior"
}

quotes = [
    ("Phinn", "I wanna catch butterflies"),
    ("Phinn", "Slow down and smell the flowers"),
    ("Phinn", "I prefer to take my time"),
    ("Phinn", "Eraaaah"),
    ("Phinn", "Hahahahaha, it tickles"),
    ("Phinn", "Something smells fishy"),
    ("Phinn", "grrrrrrmmmmmrrrrmmm rumbly(?)"),
    ("Phinn", "None of these merchants sell fish cakes" ),
    ("Phinn", "I would love a good fish brownie"),
    ("Phinn", "Ready or not, here we are"),
    ("Phinn", "When is tea Time"),
    ("Phinn", "Mostly I'm guilty by association"),
    ("Phinn", "Slow and steady wins the race"),
    ("Phinn", "Pardon me, exuse me, pardon"),
    ("Phinn", "Everybody move"),
    ("Phinn", "Lets rest awhile we can win later"),
    ("Phinn", "As long as I'm here i might as well kill you"),
    ("Phinn", "I'm mostly guilty by association")
]
